input {
    tcp {
        port => 5000
        codec => json
    }

    kafka {
        bootstrap_servers => "kafka:9092"
        topics => ["order-created", "order-confirmed", "order-delivered"]
        group_id => "logstash-consumer"
        codec => json
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "microservices-logs-%{+YYYY.MM.dd}"
    }
}